export const columnDefsResume = [
  {
    headerName: "Name",
    field: "name",
    sortable: true,
    sortingOrder: ["asc", "desc"],
    filter: true,
    width: 150,
    unSortIcon: true,
  },
  {
    headerName: "Email",
    field: "email",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    filter: true,
    unSortIcon: true,
    width: 110,
  },
  {
    headerName: "Designation",
    field: "designation",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    filter: true,
    unSortIcon: true,
    width: 110,
  },
  {
    headerName: "Skills",
    field: "skills",
    sortable: false,
    filter: true,
    width: 110,
  },
  {
    headerName: "View",
    cellRenderer: "buttonRendererViewResume",
  },
  {
    headerName: "Download",
    cellRenderer: "buttonRendererDownloadResume",
  },
  {
    headerName: "Share",
    cellRenderer: "buttonRendererShareResume",
  },
  {
    headerName: "Delete",
    cellRenderer: "buttonRendererDeleteResume",
  },
];

export const columnDefsUser = [
  {
    headerName: "Name",
    field: "name",
    unSortIcon: true,
    sortable: true,
    sortingOrder: ["asc", "desc"],
    filter: true,
    width: 150,
  },
  {
    headerName: "Email",
    field: "email",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    unSortIcon: true,
    filter: true,
    width: 110,
  },
  {
    headerName: "Role",
    field: "role",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    unSortIcon: true,
    filter: true,
    width: 110,
  },
  {
    headerName: "Status",
    field: "status",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    unSortIcon: true,
    filter: true,
    width: 110,
  },

  {
    headerName: "View",
    cellRenderer: "buttonRendererViewResume",
  },
  {
    headerName: "Delete",
    cellRenderer: "buttonRendererDeleteResume",
  },
];

export const columnDefsFeedback = [
  {
    headerName: "Candidate",
    field: "candidate",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    unSortIcon: true,
    filter: true,
    width: 110,
  },
  {
    headerName: "Interview Type",
    field: "interviewType",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    unSortIcon: true,
    filter: true,
    width: 110,
  },
  {
    headerName: "Interview Round",
    field: "interviewRound",
    sortingOrder: ["asc", "desc"],
    sortable: true,
    unSortIcon: true,
    filter: true,
    width: 110,
  },
  {
    headerName: "Interviewer",
    field: "interviewer",
    sortable: true,
    sortingOrder: ["asc", "desc"],
    filter: true,
    unSortIcon: true,
    width: 150,
  },
  {
    headerName: "Status",
    field: "status",
    sortable: true,
    sortingOrder: ["asc", "desc"],
    filter: true,
    unSortIcon: true,
    width: 150,
  },
  {
    headerName: "Submitted Date",
    field: "submittedDate",
    sortable: true,
    sortingOrder: ["asc", "desc"],
    filter: true,
    unSortIcon: true,
    width: 150,
  }, 
  {
    headerName: "View",
    cellRenderer: "buttonRendererViewResume",
  },
  {
    headerName: "Share",
    cellRenderer: "buttonRendererShareResume",
  },
  {
    headerName: "Delete",
    cellRenderer: "buttonRendererDeleteResume",
  },
];
